apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: python-app-blue
images:
- name: blue-green
  newName: tarasssito/blue-green
  newTag: 089200c7211fe9389aca320d5d9af4b2ec385542
